export default {
	MANAGE_GUILD: "Manage Server",
	CREATE_INSTANT_INVITE: "Create Invite",
	KICK_MEMBERS: "Kick Members",
	BAN_MEMBERS: "Ban Members",
	ADMINISTRATOR: "Administrator",
	MANAGE_CHANNELS: "Manage Channels",
	ADD_REACTIONS: "Add Reactions",
	VIEW_AUDIT_LOG: "View Audit Logs",
	PRIORITY_SPEAKER: "Priority Speaker",
	STREAM: "Stream",
	VIEW_CHANNEL: "View Channel",
	SEND_MESSAGES: "Send Messages",
	SEND_TTS_MESSAGES: "Send TTS Messages",
	MANAGE_MESSAGES: "Manage Messages",
	EMBED_LINKS: "Embed Links",
	ATTACH_FILES: "Attach Files",
	READ_MESSAGE_HISTORY: "View Message History",
	MENTION_EVERYONE: "Ping Everyone",
	USE_EXTERNAL_EMOJIS: "Use External Emojis",
	VIEW_GUILD_INSIGHTS: "View Guild Insights",
	CONNECT: "Connect to a Voice Channel",
	SPEAK: "Speak in a Voice Channel",
	MUTE_MEMBERS: "Mute Members",
	DEAFEN_MEMBERS: "Deafen Members",
	MOVE_MEMBERS: "Move Members",
	USE_VAD: "Use Voice Activity Detection",
	CHANGE_NICKNAME: "Change Nickname",
	MANAGE_NICKNAMES: "Manage Nicknames",
	MANAGE_ROLES: "Manage Roles",
	MANAGE_WEBHOOKS: "Manage Webhooks",
	MANAGE_EMOJIS_AND_STICKERS: "Manage Emojis and Stickers",
	REQUEST_TO_SPEAK: "Request To Speak In Stage Channels",
	USE_APPLICATION_COMMANDS: "Use Slash Commands",
	MANAGE_EVENTS: "Manage Events",
	MANAGE_THREADS: "Manage Threads",
	USE_PUBLIC_THREADS: "Use Public Threads",
	CREATE_PUBLIC_THREADS: "Create Public Threads",
	USE_PRIVATE_THREADS: "Use Private Threads",
	CREATE_PRIVATE_THREADS: "Create Private Threads",
	USE_EXTERNAL_STICKERS: "Use External Stickers",
	SEND_MESSAGES_IN_THREADS: "Send Messages in Threads",
	START_EMBEDDED_ACTIVITIES: "Start Embedded Activities",
	MODERATE_MEMBERS: "Moderate Members"
};
